# Generated by Django 5.0.2 on 2024-02-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_hobies_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hobies',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
