# Generated by Django 5.0.2 on 2024-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_hobies_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='slug',
            new_name='yol',
        ),
        migrations.RenameField(
            model_name='hobies',
            old_name='slug',
            new_name='yol',
        ),
        migrations.AlterField(
            model_name='hobies',
            name='image',
            field=models.ImageField(upload_to='blog_images'),
        ),
    ]
