# Generated by Django 5.0.2 on 2024-02-18 20:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_slug_categories_yol_rename_slug_hobies_yol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobies',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
