# Generated by Django 5.0.2 on 2024-02-18 21:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_hobies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobies',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
