# Generated by Django 5.0.2 on 2024-02-18 21:59

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_hobies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobies',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
