# Generated by Django 5.0.2 on 2024-02-20 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_hobies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobies',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.categories'),
        ),
    ]
